### ISSUE TITLE
Use multiple filters and adjust only one of them (using a seek bar)

### ISSUE THREAD

**Issue by NiekAkerboom** [wysaid/android-gpuimage-plus#133] opened 2017-06-14 13:20 UTC
What would be the proper way to have multiple filters, for example:

`String config = "@adjust lut bleach.png @adjust exposure 0.5 @adjust warmth 0.5 @adjust shadowhighlight 100 100";`

and then only change the intensity of one of them? [Here's a screenshot of my example app](http://i.imgur.com/GYepprw.jpg). Applying the filters feels quite slow when changing the seek bar's values. I'm probably doing something wrong as in it's recreating/adjusting the other filters as well.

It looks like it's doing something like I want in the provided CGE Tools (Generator).

Thanks for your help.

**Comment by wysaid** [comment] 2017-06-15 02:04
I know what you want.
I will add a test case to do this soon.
If you are good at OpenGL, you can do it like this:
>1. Use [CGENativeLibrary.cgeCreateFilterWithConfig](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/nativePort/CGENativeLibrary.java#L161) to generate the filter, keep the return value.

>2. Take a look at the [CGEImageHandler.processWithFilter](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/nativePort/CGEImageHandler.java#L93) function. Get the instance of __CGEImageHandler__ in [ImageGLSurfaceView](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/view/ImageGLSurfaceView.java#L37)

>3. You should generate the three filters, and run them following the ImageGLSurfaceView does. And you should add an intensity setter for them anywhere.

**Comment by NiekAkerboom** [comment] 2017-06-15 12:13
Thank you for helping me out, but I can't seem to get your new method to work.

When running the following:
`mImageSurfaceView.setFilterWithConfig("@adjust warmth 4.0 @adjust exposure 1 @adjust saturation 0.7")`
Later followed by:
`mImageSurfaceView.setFilterIntensityForIndex(0.5, 0)`
Then all 3 the filters are still being changed instead of just the first (warmth) one.

I added the following log at [cgeImageHandlerWrapper.cpp#L134
](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/interface/cgeImageHandlerWrapper.cpp#L134)`__android_log_print(ANDROID_LOG_VERBOSE, APPNAME, "amount of filters is %d", filters.size());`
And the filter size always returns 1 no matter how many filters I apply.

Am I missing something here?

**Comment by NiekAkerboom** [comment] 2017-06-15 18:19
One issue that I'm still having is that it looks 'slow'. I made a video where you can see my concern: https://youtu.be/4iTlHVi0VKQ

Is this a known issue or am I doing something wrong? I don't have these issues when using "android-gpuimage" by CyberAgent, I can wire up 10+ filters and it feels grand.

**Comment by wysaid** [comment] 2017-06-16 01:56
@NiekAkerboom 
__setFilterWithConfig__ should only be called once if you do not change the filter type.

**Comment by wysaid** [comment] 2017-06-16 02:13
Change [line 87 of ImageGLSurfaceView](https://github.com/wysaid/android-gpuimage-plus/blob/a50436bd0a16ee804a5a6b9c4fcdd79d142036df/library/src/main/java/org/wysaid/view/ImageGLSurfaceView.java#L87) to
>protected int mSettingIntensityCount = 1;

May solve your problem.

**Comment by NiekAkerboom** [comment] 2017-06-16 09:47
Setting mSettingIntensityCount to 1 indeed fixed it, thank you very much for the swift response!

**Comment by divysoni3** [comment] 2017-07-07 13:19
@NiekAkerboom will u please explain how did u add filters individually as u mentioned above. 
> Yes, yes I was missing something. I didn't know that the config string doesn't get added as single filters. Once I add them individually it does work and the amount of filters log returns 3.

Is there any other way to add filter individually other than this
`mImageSurfaceView.setFilterWithConfig("@adjust warmth 4.0 @adjust exposure 1 @adjust saturation 0.7")`

**Comment by wysaid** [comment] 2017-07-07 14:41
@divysoni3 @NiekAkerboom 
It's fixed by this commit: https://github.com/wysaid/android-gpuimage-plus/commit/3c3fe1b44ab3dc908185c15432d7990c897c5421
Please pull the code.

**Comment by wysaid** [comment] 2017-07-07 16:52
This feature is done: https://github.com/wysaid/android-gpuimage-plus/commit/76434125c8e545a025ca9bd948d324f40293e9a1
The first case just do it.

**Comment by divysoni3** [comment] 2017-07-10 05:58
Thanks @wysaid now crash is resolved, but `setFilterIntensity(0.5)` and `setFilterIntensityForIndex(0.5, 0)` are behaving differently..
In ImageDemoActivity you are giving single effect so both of these method should give same result, but if I change line number 89 with `setFilterIntensityForIndex(0.5, 0)` this method, then it is not working with many effects.
Kindly help.

**Comment by wysaid** [comment] 2017-07-10 06:35
@divysoni3 
Hi, the two functions are doing different things.

``setFilterIntensity`` is using [CGEMutipleMixFilter](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/include/filters/cgeMultipleEffects.h#L17) to do a mix between the result and the origin by the passed intensity.

And ``setFilterIntensityForIndex`` is directly calling the virtual function [CGEImageFilterInterfaceAbstract::setIntensity](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/include/cgeImageFilter.h#L46) of the filter at the given index.

__But__ the virtual method [CGEImageFilterInterfaceAbstract::setIntensity](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/include/cgeImageFilter.h#L46) is not always implemented by the filter.  For example, the [Curve filter](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/include/filters/cgeCurveAdjust.h) did not override it, so you get nothing when called by ``setFilterIntensityForIndex`` .

It's not a bug, and you may implement this case by yourself.🙂

**Comment by divysoni3** [comment] 2017-07-10 07:00
@wysaid Actually I want to apply Basic image filters (`brightness`, `contrast `etc.) and Advanced image filters (`"@curve RGB(0,255)(255,0) @style cm mapping0.jpg 80 80 8 3"` etc.) together, user can adjust every filters intensity individually, It is working fine with Basic image filters because I know Max and Min value of every effect but in case of Advanced image filters I am unable to set intensity using index.

Can u guide me how can I do this?

**Comment by wysaid** [comment] 2017-07-10 07:39
You may need to add your own setter for different filters, because not all filters have only one argument to set. Some filters have many args to set. (such as ``selective color``)

**Comment by divysoni3** [comment] 2017-07-10 07:43
I got the Idea, Thanks for helping.

**Closed** 2017-10-24 14:40 UTC

**Comment by Ashutosh-Tiwari** [comment] 2018-02-09 11:23
@NiekAkerboom  With no relation to this issue, I wanted to know how are you entertaining `warmth` filter on image! I saw your demo video and screenshot that you shared and also say the warmth option in the config string. I tried to use similar config string but nothing changed. Any guidelines please?

**Comment by NiekAkerboom** [comment] 2018-02-09 11:53
@Ashutosh-Tiwari If there are filters that you would like to use but they don't exist in this library you'll have to make them yourself. There's a bunch of related questions here when it comes to creating custom filters.

I copied an existing filter, renamed it to cgeWarmthAdjust and edited the shader code. Also you've got to make sure that you actually parse it when calling "@adjust warmth" which you have to do in some places, for example [over here](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/cge/filters/cgeDataParsingEngine.cpp#L400). wysaid mentioned custom filters in the readme file [over here](https://github.com/wysaid/android-gpuimage-plus/#2-custom-shader-filter).

Good luck!

**Comment by Ashutosh-Tiwari** [comment] 2018-02-09 13:24
@NiekAkerboom  I wish I knew working with native code. But thanks for the explanation. I will put my efforts to get it done somehow.
